/*
 * This file is generated by jOOQ.
 */
package com.hedera.demo.auction.app.domain;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.vertx.core.json.JsonObject;
import org.jooq.Record;
import io.vertx.sqlclient.Row;

import java.io.Serializable;

import static com.hedera.demo.auction.app.db.Tables.VALIDATORS;

public class Validator implements VertxPojo, Serializable {

    private static final long serialVersionUID = -495816041;

    private String name = "";
    private String url = "";
    private String publicKey = "";

    public Validator() {}

    public Validator(Record record) {
        this.name = record.get(VALIDATORS.NAME);
        this.url = record.get(VALIDATORS.URL);
        this.publicKey = record.get(VALIDATORS.PUBLICKEY);
    }

    public Validator(Row row) {
        this.name = row.getString(VALIDATORS.NAME.getName());
        this.url = row.getString(VALIDATORS.URL.getName());
        this.publicKey = row.getString(VALIDATORS.PUBLICKEY.getName());
    }

    public Validator(JsonObject json) {
        this();
        fromJson(json);
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUrl() {
        return url;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    public String getPublicKey() {
        return publicKey;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Validators (");

        sb.append(name);
        sb.append(", ").append(url);
        sb.append(", ").append(publicKey);

        sb.append(")");
        return sb.toString();
    }

    @Override
    public Validator fromJson(JsonObject json) {
        this.setName(json.getString("name"));
        this.setUrl(json.getString("url"));
        this.setPublicKey(json.getString("publicKey"));
        return this;
    }

    @Override
    public JsonObject toJson() {
        JsonObject json = new JsonObject();
        json.put("name", name);
        json.put("url", url);
        json.put("publicKey", publicKey);
        return json;
    }
}
