version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: gradle
    directory: "/hedera-nft-auction-demo-java-node"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
