version: "3"
services:
  postgres:
    container_name: nft-auction-postgres
    build:
      context: ./docker-postgres
    restart: unless-stopped
    env_file:
      - docker-files/.env
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -c 'max_connections=100' -p 5433
    volumes:
      - ./docker-files/postgres-data:/var/lib/postgresql/data

  node:
    container_name: nft-auction-node
    build:
      context: hedera-nft-auction-demo-java-node
    restart: unless-stopped
    environment:
      # Database connection
      - DATABASE_URL=postgresql://postgres:5433/
      # Run auction node only
      - AUCTION_NODE=true
      - REST_API=false
    env_file:
      - docker-files/.env
    depends_on:
      - postgres
    volumes:
      - ./docker-files:/demo

  rest-api:
    container_name: nft-auction-rest-api
    build:
      context: hedera-nft-auction-demo-java-node
    restart: unless-stopped
    environment:
      # Run API only
      - REST_API=true
      - AUCTION_NODE=false
      # Database connection
      - DATABASE_URL=postgresql://postgres:5433/
      # REST API Ports
      - API_PORT=8081
      - API_VERTICLE_COUNT=3
      - ADMIN_API_PORT=8082
      - ADMIN_API_VERTICLE_COUNT=1
    env_file:
      - docker-files/.env
    expose:
      - 8081
      - 8082
    depends_on:
      - postgres
    volumes:
      - ./docker-files:/demo

  ui:
    container_name: nft-auction-ui
    build:
      context: hedera-nft-auction-demo-javascript-client
    restart: unless-stopped
    env_file:
      - docker-files/.env
    expose:
      - 3000

  proxy:
    container_name: nft-auction-nginx-proxy
    build:
      context: docker-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ui
      - rest-api
    volumes:
      - ./docker-files:/demo
      - ./docker-files/conf.d:/etc/nginx/conf.d/
