/*
 * This file is generated by jOOQ.
 */
package com.hedera.demo.auction.app.db;


import com.hedera.demo.auction.app.db.tables.Auctions;
import com.hedera.demo.auction.app.db.tables.Bids;
import com.hedera.demo.auction.app.db.tables.FlywaySchemaHistory;
import com.hedera.demo.auction.app.db.tables.Scheduledoperations;

import org.jooq.ForeignKey;
import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> AUCTIONS_AUCTIONACCOUNTID_KEY = Internal.createUniqueKey(Auctions.AUCTIONS, DSL.name("auctions_auctionaccountid_key"), new TableField[] { Auctions.AUCTIONS.AUCTIONACCOUNTID }, true);
    public static final UniqueKey<Record> AUCTIONS_PKEY = Internal.createUniqueKey(Auctions.AUCTIONS, DSL.name("auctions_pkey"), new TableField[] { Auctions.AUCTIONS.ID }, true);
    public static final UniqueKey<Record> AUCTIONS_TOKENID_KEY = Internal.createUniqueKey(Auctions.AUCTIONS, DSL.name("auctions_tokenid_key"), new TableField[] { Auctions.AUCTIONS.TOKENID }, true);
    public static final UniqueKey<Record> BIDS_PKEY = Internal.createUniqueKey(Bids.BIDS, DSL.name("bids_pkey"), new TableField[] { Bids.BIDS.TIMESTAMP }, true);
    public static final UniqueKey<Record> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<Record> SCHEDULEDOPERATIONS_TRANSACTIONID_KEY = Internal.createUniqueKey(Scheduledoperations.SCHEDULEDOPERATIONS, DSL.name("scheduledoperations_transactionid_key"), new TableField[] { Scheduledoperations.SCHEDULEDOPERATIONS.TRANSACTIONID }, true);
    public static final UniqueKey<Record> SCHEDULEDOPERATIONS_TRANSACTIONTIMESTAMP_KEY = Internal.createUniqueKey(Scheduledoperations.SCHEDULEDOPERATIONS, DSL.name("scheduledoperations_transactiontimestamp_key"), new TableField[] { Scheduledoperations.SCHEDULEDOPERATIONS.TRANSACTIONTIMESTAMP }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<Record, Record> BIDS__BIDS_AUCTIONID_FKEY = Internal.createForeignKey(Bids.BIDS, DSL.name("bids_auctionid_fkey"), new TableField[] { Bids.BIDS.AUCTIONID }, Keys.AUCTIONS_PKEY, new TableField[] { Auctions.AUCTIONS.ID }, true);
}
