/*
 * This file is generated by jOOQ.
 */
package com.hedera.demo.auction.app.db;


import com.hedera.demo.auction.app.db.tables.Auctions;
import com.hedera.demo.auction.app.db.tables.Bids;
import com.hedera.demo.auction.app.db.tables.FlywaySchemaHistory;
import com.hedera.demo.auction.app.db.tables.Validators;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.auctions</code>.
     */
    public final Auctions AUCTIONS = Auctions.AUCTIONS;

    /**
     * The table <code>public.bids</code>.
     */
    public final Bids BIDS = Bids.BIDS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.validators</code>.
     */
    public final Validators VALIDATORS = Validators.VALIDATORS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.AUCTIONS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Auctions.AUCTIONS,
            Bids.BIDS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Validators.VALIDATORS);
    }
}
