/*
 * This file is generated by jOOQ.
 */
package com.hedera.demo.auction.app.db;


import com.hedera.demo.auction.app.db.tables.Auctions;
import com.hedera.demo.auction.app.db.tables.Bids;
import com.hedera.demo.auction.app.db.tables.FlywaySchemaHistory;
import com.hedera.demo.auction.app.db.tables.Validators;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.auctions</code>.
     */
    public static final Auctions AUCTIONS = Auctions.AUCTIONS;

    /**
     * The table <code>public.bids</code>.
     */
    public static final Bids BIDS = Bids.BIDS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.validators</code>.
     */
    public static final Validators VALIDATORS = Validators.VALIDATORS;
}
