/*
 * This file is generated by jOOQ.
 */
package com.hedera.demo.auction.app.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Bids implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String timestamp;
    private final Integer auctionid;
    private final String bidderaccountid;
    private final Long bidamount;
    private final String status;
    private final String refundtxid;
    private final String refundtxhash;
    private final String transactionid;
    private final String transactionhash;
    private final String refundstatus;
    private final String scheduleid;

    public Bids(Bids value) {
        this.timestamp = value.timestamp;
        this.auctionid = value.auctionid;
        this.bidderaccountid = value.bidderaccountid;
        this.bidamount = value.bidamount;
        this.status = value.status;
        this.refundtxid = value.refundtxid;
        this.refundtxhash = value.refundtxhash;
        this.transactionid = value.transactionid;
        this.transactionhash = value.transactionhash;
        this.refundstatus = value.refundstatus;
        this.scheduleid = value.scheduleid;
    }

    public Bids(
        String timestamp,
        Integer auctionid,
        String bidderaccountid,
        Long bidamount,
        String status,
        String refundtxid,
        String refundtxhash,
        String transactionid,
        String transactionhash,
        String refundstatus,
        String scheduleid
    ) {
        this.timestamp = timestamp;
        this.auctionid = auctionid;
        this.bidderaccountid = bidderaccountid;
        this.bidamount = bidamount;
        this.status = status;
        this.refundtxid = refundtxid;
        this.refundtxhash = refundtxhash;
        this.transactionid = transactionid;
        this.transactionhash = transactionhash;
        this.refundstatus = refundstatus;
        this.scheduleid = scheduleid;
    }

    /**
     * Getter for <code>public.bids.timestamp</code>.
     */
    public String getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>public.bids.auctionid</code>.
     */
    public Integer getAuctionid() {
        return this.auctionid;
    }

    /**
     * Getter for <code>public.bids.bidderaccountid</code>.
     */
    public String getBidderaccountid() {
        return this.bidderaccountid;
    }

    /**
     * Getter for <code>public.bids.bidamount</code>.
     */
    public Long getBidamount() {
        return this.bidamount;
    }

    /**
     * Getter for <code>public.bids.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.bids.refundtxid</code>.
     */
    public String getRefundtxid() {
        return this.refundtxid;
    }

    /**
     * Getter for <code>public.bids.refundtxhash</code>.
     */
    public String getRefundtxhash() {
        return this.refundtxhash;
    }

    /**
     * Getter for <code>public.bids.transactionid</code>.
     */
    public String getTransactionid() {
        return this.transactionid;
    }

    /**
     * Getter for <code>public.bids.transactionhash</code>.
     */
    public String getTransactionhash() {
        return this.transactionhash;
    }

    /**
     * Getter for <code>public.bids.refundstatus</code>.
     */
    public String getRefundstatus() {
        return this.refundstatus;
    }

    /**
     * Getter for <code>public.bids.scheduleid</code>.
     */
    public String getScheduleid() {
        return this.scheduleid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Bids other = (Bids) obj;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.auctionid == null) {
            if (other.auctionid != null)
                return false;
        }
        else if (!this.auctionid.equals(other.auctionid))
            return false;
        if (this.bidderaccountid == null) {
            if (other.bidderaccountid != null)
                return false;
        }
        else if (!this.bidderaccountid.equals(other.bidderaccountid))
            return false;
        if (this.bidamount == null) {
            if (other.bidamount != null)
                return false;
        }
        else if (!this.bidamount.equals(other.bidamount))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.refundtxid == null) {
            if (other.refundtxid != null)
                return false;
        }
        else if (!this.refundtxid.equals(other.refundtxid))
            return false;
        if (this.refundtxhash == null) {
            if (other.refundtxhash != null)
                return false;
        }
        else if (!this.refundtxhash.equals(other.refundtxhash))
            return false;
        if (this.transactionid == null) {
            if (other.transactionid != null)
                return false;
        }
        else if (!this.transactionid.equals(other.transactionid))
            return false;
        if (this.transactionhash == null) {
            if (other.transactionhash != null)
                return false;
        }
        else if (!this.transactionhash.equals(other.transactionhash))
            return false;
        if (this.refundstatus == null) {
            if (other.refundstatus != null)
                return false;
        }
        else if (!this.refundstatus.equals(other.refundstatus))
            return false;
        if (this.scheduleid == null) {
            if (other.scheduleid != null)
                return false;
        }
        else if (!this.scheduleid.equals(other.scheduleid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.auctionid == null) ? 0 : this.auctionid.hashCode());
        result = prime * result + ((this.bidderaccountid == null) ? 0 : this.bidderaccountid.hashCode());
        result = prime * result + ((this.bidamount == null) ? 0 : this.bidamount.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.refundtxid == null) ? 0 : this.refundtxid.hashCode());
        result = prime * result + ((this.refundtxhash == null) ? 0 : this.refundtxhash.hashCode());
        result = prime * result + ((this.transactionid == null) ? 0 : this.transactionid.hashCode());
        result = prime * result + ((this.transactionhash == null) ? 0 : this.transactionhash.hashCode());
        result = prime * result + ((this.refundstatus == null) ? 0 : this.refundstatus.hashCode());
        result = prime * result + ((this.scheduleid == null) ? 0 : this.scheduleid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Bids (");

        sb.append(timestamp);
        sb.append(", ").append(auctionid);
        sb.append(", ").append(bidderaccountid);
        sb.append(", ").append(bidamount);
        sb.append(", ").append(status);
        sb.append(", ").append(refundtxid);
        sb.append(", ").append(refundtxhash);
        sb.append(", ").append(transactionid);
        sb.append(", ").append(transactionhash);
        sb.append(", ").append(refundstatus);
        sb.append(", ").append(scheduleid);

        sb.append(")");
        return sb.toString();
    }
}
