/*
 * This file is generated by jOOQ.
 */
package com.hedera.demo.auction.app.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Validators implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String name;
    private final String url;
    private final String publickey;

    public Validators(Validators value) {
        this.name = value.name;
        this.url = value.url;
        this.publickey = value.publickey;
    }

    public Validators(
        String name,
        String url,
        String publickey
    ) {
        this.name = name;
        this.url = url;
        this.publickey = publickey;
    }

    /**
     * Getter for <code>public.validators.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.validators.url</code>.
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Getter for <code>public.validators.publickey</code>.
     */
    public String getPublickey() {
        return this.publickey;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Validators other = (Validators) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.publickey == null) {
            if (other.publickey != null)
                return false;
        }
        else if (!this.publickey.equals(other.publickey))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.publickey == null) ? 0 : this.publickey.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Validators (");

        sb.append(name);
        sb.append(", ").append(url);
        sb.append(", ").append(publickey);

        sb.append(")");
        return sb.toString();
    }
}
