FROM adoptopenjdk:14-jre-hotspot

COPY hedera-nft-auction-demo-node-1.0.jar /srv/hedera-nft-auction-demo-node-1.0.jar

#ENTRYPOINT ["tail", "-f", "/dev/null"]

#CMD java -jar hedera-nft-auction-demo-node-1.0.jar
CMD [ "java", "-jar", "/srv/hedera-nft-auction-demo-node-1.0.jar" ]
#CMD "java" "-jar" "hedera-nft-auction-demo-node-1.0.jar"
