/*
 * This file is generated by jOOQ.
 */
package com.hedera.demo.auction.app.db.tables;


import com.hedera.demo.auction.app.db.Keys;
import com.hedera.demo.auction.app.db.Public;
import com.hedera.demo.auction.app.db.tables.Bids.BidsPath;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Auctions extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.auctions</code>
     */
    public static final Auctions AUCTIONS = new Auctions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.auctions.id</code>.
     */
    public final TableField<Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.auctions.lastconsensustimestamp</code>.
     */
    public final TableField<Record, String> LASTCONSENSUSTIMESTAMP = createField(DSL.name("lastconsensustimestamp"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("'0.0'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.winningbid</code>.
     */
    public final TableField<Record, Long> WINNINGBID = createField(DSL.name("winningbid"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.auctions.winningaccount</code>.
     */
    public final TableField<Record, String> WINNINGACCOUNT = createField(DSL.name("winningaccount"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.winningtimestamp</code>.
     */
    public final TableField<Record, String> WINNINGTIMESTAMP = createField(DSL.name("winningtimestamp"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.winningtxid</code>.
     */
    public final TableField<Record, String> WINNINGTXID = createField(DSL.name("winningtxid"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.winningtxhash</code>.
     */
    public final TableField<Record, String> WINNINGTXHASH = createField(DSL.name("winningtxhash"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.transfertxid</code>.
     */
    public final TableField<Record, String> TRANSFERTXID = createField(DSL.name("transfertxid"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.transfertxhash</code>.
     */
    public final TableField<Record, String> TRANSFERTXHASH = createField(DSL.name("transfertxhash"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.tokenid</code>.
     */
    public final TableField<Record, String> TOKENID = createField(DSL.name("tokenid"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.auctionaccountid</code>.
     */
    public final TableField<Record, String> AUCTIONACCOUNTID = createField(DSL.name("auctionaccountid"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.endtimestamp</code>.
     */
    public final TableField<Record, String> ENDTIMESTAMP = createField(DSL.name("endtimestamp"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.reserve</code>.
     */
    public final TableField<Record, Long> RESERVE = createField(DSL.name("reserve"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.auctions.status</code>.
     */
    public final TableField<Record, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("'PENDING'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.winnercanbid</code>.
     */
    public final TableField<Record, Boolean> WINNERCANBID = createField(DSL.name("winnercanbid"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.auctions.tokenmetadata</code>.
     */
    public final TableField<Record, String> TOKENMETADATA = createField(DSL.name("tokenmetadata"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.minimumbid</code>.
     */
    public final TableField<Record, Long> MINIMUMBID = createField(DSL.name("minimumbid"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.auctions.starttimestamp</code>.
     */
    public final TableField<Record, String> STARTTIMESTAMP = createField(DSL.name("starttimestamp"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.tokenowner</code>.
     */
    public final TableField<Record, String> TOKENOWNER = createField(DSL.name("tokenowner"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.transferstatus</code>.
     */
    public final TableField<Record, String> TRANSFERSTATUS = createField(DSL.name("transferstatus"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.title</code>.
     */
    public final TableField<Record, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.description</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.auctions.processrefunds</code>.
     */
    public final TableField<Record, Boolean> PROCESSREFUNDS = createField(DSL.name("processrefunds"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.auctions.createauctiontxid</code>.
     */
    public final TableField<Record, String> CREATEAUCTIONTXID = createField(DSL.name("createauctiontxid"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    private Auctions(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Auctions(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.auctions</code> table reference
     */
    public Auctions(String alias) {
        this(DSL.name(alias), AUCTIONS);
    }

    /**
     * Create an aliased <code>public.auctions</code> table reference
     */
    public Auctions(Name alias) {
        this(alias, AUCTIONS);
    }

    /**
     * Create a <code>public.auctions</code> table reference
     */
    public Auctions() {
        this(DSL.name("auctions"), null);
    }

    public <O extends Record> Auctions(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, AUCTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuctionsPath extends Auctions implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuctionsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuctionsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuctionsPath as(String alias) {
            return new AuctionsPath(DSL.name(alias), this);
        }

        @Override
        public AuctionsPath as(Name alias) {
            return new AuctionsPath(alias, this);
        }

        @Override
        public AuctionsPath as(Table<?> alias) {
            return new AuctionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return (Identity<Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.AUCTIONS_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.AUCTIONS_AUCTIONACCOUNTID_KEY, Keys.AUCTIONS_TOKENID_KEY);
    }

    private transient BidsPath _bids;

    /**
     * Get the implicit to-many join path to the <code>public.bids</code> table
     */
    public BidsPath bids() {
        if (_bids == null)
            _bids = new BidsPath(this, null, Keys.BIDS__BIDS_AUCTIONID_FKEY.getInverseKey());

        return _bids;
    }

    @Override
    public Auctions as(String alias) {
        return new Auctions(DSL.name(alias), this);
    }

    @Override
    public Auctions as(Name alias) {
        return new Auctions(alias, this);
    }

    @Override
    public Auctions as(Table<?> alias) {
        return new Auctions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Auctions rename(String name) {
        return new Auctions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Auctions rename(Name name) {
        return new Auctions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Auctions rename(Table<?> name) {
        return new Auctions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions where(Condition condition) {
        return new Auctions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Auctions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Auctions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Auctions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Auctions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Auctions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
